### PR TITLE
Image optimisation

### PR DESCRIPTION
**Pull request by addyosmani**
Heya. First, y'all are doing SO much better on your WebPageTest benchmarks for desktop this year. Nice work! Let's take it further!

screen shot 2015-01-30 at 10 12 34

This PR includes a few image optimisations:
- Shaves 100KB off the profile image for Malte. As we're only using a max-width of 240px for organisers we don't need a more high-res version in there.
- Shaves 80KB off Jan's profile picture (PNG -> 90%, progressive JPG)
- Optimises the rest of the images by an average of 3%

Hoping it helps a little with this PageSpeed Insights report for mobile:

screen shot 2015-01-30 at 10 16 56

### CODE REVIEW

**Comment by janl** [comment]
<3 <3 <3

**Comment by addyosmani** [comment]
<3333

**Comment by theophani** [comment]
:icecream:

**Comment by rendro** [comment]
:+1:

**Comment by azizarslan** [comment]
:kiss:

**Comment by smtaydemir** [comment]
💘

**Comment by delirehberi** [comment]
:heart:

**Pull request merged**
